require "csv"

CSV.foreach('db/tour.csv') do |row|
  Tour.create(:name_ja => row[0], :name_en => row[1],
  :category_ja => row[2],
  :category_en => row[3],
  :description_ja => row[4],   :apply_startdate => row[6],   :apply_enddate => row[7],
  :area_ja => row[8],
  :area_en => row[9],
  :price_ja => row[10],
  :price_en => row[11],
  :lang_japanese => row[12],
  :lang_english => row[13],
  :lang_others_ja => row[14],
  :lang_others_en => row[15],
  :companyname_ja => row[16],
  :companyname_en => row[17],
  :url_info => row[18],
  :picture1 => row[19],
  :picture2 => row[20],
  :picture3 => row[21],
  :picture4 => row[22],
  :total_acttime => row[23],
  :cancel_policy_ja => row[24],
  :cancel_policy_en => row[25],
  :payment_method_ja => row[26],
  :payment_method_en => row[27],
  :note_ja => row[28],
  :note_en => row[29],
  :meeting_time => row[30],
  :meeting_place_ja => row[31],
  :meeting_place_en => row[32],
  :meeting_address => row[33],
  :meeting_mapurl => row[34],
  :activity1_time => row[35],
  :activity1_action => row[36],
  :activity1_explanation => row[37],
  :activity1_picture => row[38],
  :activity2_time => row[39],
  :activity2_action => row[40],
  :activity2_explanation => row[41],
  :activity2_picture => row[42],
  :activity3_time => row[43],
  :activity3_action => row[44],
  :activity3_explanation => row[45],
  :activity3_picture => row[46],
  :activity4_time => row[47],
  :activity4_action => row[48],
  :activity4_explanation => row[49],
  :activity4_picture => row[50],
  :activity5_time => row[51],
  :activity5_action => row[52],
  :activity5_explanation => row[53],
  :activity5_picture => row[54]
 )
end